### ISSUE TITLE
Add TypeScript type definitions

### ISSUE THREAD

**Issue by babeal** [blesh/redux-observable#12]
Do you plan to add typings for this library?

**Comment by jayphelps** [comment]
No existing plans, but certainly if there's desire we hopefully will get around to it, or someone in the community will.

**Comment by bennett000** [comment]
@babeal there are now two PR's up that address this.  We ended up working on them simultaneously.  Happy Saturday.

**Comment by babeal** [comment]
@bennett000 that's great.  I'm glad I waited and wasn't the third.
