### ISSUE TITLE
Ben, please enable greenkeeper

### ISSUE THREAD

**Issue by jayphelps** [blesh/redux-observable#16]
A new eslint release today broke up build, as described in #14. https://greenkeeper.io is free for open source and will automatically check for these kinds of things and warn us via PR. Here's an example: https://github.com/FreeCodeCamp/FreeCodeCamp/pull/8617

It's pretty amazing. Only the repo owner (not collaborators) can enable it, so you'll need to do it. Instructions are easy.

https://greenkeeper.io/#getting-started

## GETTING  STARTED

Three simple commands: Open your terminal, and
```
$ npm install -g greenkeeper
$ greenkeeper login
```
Your browser will open and ask you to log in to GitHub. Please do that.

Then, inside the repo you want to keep up to date, do
```
$ greenkeeper enable
```
and you’re done! Your first greenkeeper PR will arrive shortly!

**Comment by blesh** [comment]
```
gml-blesh:redux-observable blesh$ greenkeeper enable
🌴  info enable The GitHub slug is: blesh/redux-observable
blesh/redux-observable enabled
```

Done
