### ISSUE TITLE
Merge strategy factories (higher-order thunkservables)

### ISSUE THREAD

**Issue by blesh** [blesh/redux-observable#9]
### Problem

Basically, just need a cleaner way to handle composed cancellation via something like a "switch" map. Generally in Rx these are referred to as "merge strategies". 

Conceptually they'd look like this:

```js
const switch = (thunkservable)  => {
  let subject = new Subject();
  let subscription;
  return (actions, store) => {
    if (subscription) {
      subscription.unsubscribe() 
    }
    subscription = thunkservable(actions,store).subscribe(::subject.next);
    return subject;
  };
}

const merge = (thunkservable, concurrency = Number.POSITIVE_INFINITY) => {
  let subject = new Subject();
  let merged = subject.mergeAll(concurrency);
  return (actions, store) => {
    subject.next(thunkservable(actions, store));
    return merged;
  };
}

const concat = (thunkservable) => {
  return merge(thunkservable, 1);
}
```

And would be used as such:

```js
let sendAutoComplete = (q) => switch(() => Observable.ajax.get(`some/endpoint${q}`));
```

**Comment by jayphelps** [comment]
Until someone recommends a better approach, this is a huge 👍 from me. Next issue is what to call them.

Something like `switchFactory` etc but that's not a verb. 🚲

**Comment by blesh** [comment]
Turns out `switch` is an unfriendly name. Also the implementation of `switch` above could be like the `merge` impl below it.

**Comment by blesh** [comment]
And "turns out", those other implementations are silly because they're nexting a value synchronously into the subject _prior_ to returning them. :\ Lame.

**Comment by blesh** [comment]
There are other issues with this approach so far. The biggest being reuse.

so if you have a merge strategy HO thunkservable: 

```js
var switched = switch((actions, store) => Observable.timer(1000).mapTo({ type: 'TEST' }));
```

and you want to provide some argument to it, it become harder, because in the below scenario you're actually creating a new switching context each time, and the switch doesn't occur anyhow.

```js
var switched = (value) => switch((actions, store) => Observable.timer(1000).mapTo({ type: 'TEST', value }));
```

**Comment by blesh** [comment]
Looking into this further. I think we can accomplish this in a different way:

Simply dispatching when the component mounts:

```js
dispatch(() => keyups.map(e => e.target.value)
  .throttleTime(500)
  .switchMap((value) => getAutoComplete(value))
  .map((data) => ({ type: 'AUTOCOMPLETE_RESULTS', data })
```

I think this is probably the preferable method, as my above proposed methods feel clunky and gross now that I'm playing with them.

I'm going to close this issue for now. We should probably create an example with the idiomatic RxJS autocomplete, because it's not straightforward at first blush.
